### ISSUE TITLE
First steps with your code

### ISSUE THREAD

**Issue by erlebach** [MCooperBorkenhagen/dissertation#2]
Issue removed.

**Comment by MCooperBorkenhagen** [comment]
Hello Gordon. Can you remove this issue and hold off a couple days, please? If you want to just look around, you can check out `Learner.py`. Nathan and I need to meet and establish a few preliminaries before we get moving on this. Also, this development will happen in a separate repository, to which you and your team will be contributors. The work won't be happening in this repository. Before we start collaborating together in GitHub, you can reach me for communication at `mcooperborkenhagen@fsu.edu`. Copy Nathan on emails there, please. Thank you.
